/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TELAS;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author v
 */
public class Tela_Principal_Administrador extends javax.swing.JDialog {

    /**
     * Creates new form adm
     */
    public Tela_Principal_Administrador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jldata = new javax.swing.JLabel();
        jlhora = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        jMenuItem12.setText("jMenuItem12");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                aoabrirtela(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TELAS/IMAGENS/admin_person_user_man_2839.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jldata)
                .addGap(18, 18, 18)
                .addComponent(jlhora))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(56, 56, 56))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlhora)
                    .addComponent(jldata))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TELAS/IMAGENS/Document_Write_26983.png"))); // NOI18N
        jMenu3.setText("Cadastrar & Buscar");

        jMenuItem13.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TELAS/IMAGENS/animal_panda_2737.png"))); // NOI18N
        jMenuItem13.setText("Animal");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirtelaanimal(evt);
            }
        });
        jMenu3.add(jMenuItem13);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TELAS/IMAGENS/travel_journey_icon-icons.com_55995.png"))); // NOI18N
        jMenuItem10.setText("Boletim Diario");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10telaboletimdiario(evt);
            }
        });
        jMenu3.add(jMenuItem10);

        jMenuItem16.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TELAS/IMAGENS/Accept-icon.png"))); // NOI18N
        jMenuItem16.setText("CheckList");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16aobrircheck(evt);
            }
        });
        jMenu3.add(jMenuItem16);

        jMenuItem15.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TELAS/IMAGENS/equipemenuiconnossalondres.png"))); // NOI18N
        jMenuItem15.setText("Equipe");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ttelaequipe(evt);
            }
        });
        jMenu3.add(jMenuItem15);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TELAS/IMAGENS/task_list_19659.png"))); // NOI18N
        jMenuItem9.setText("Tarefa");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9telatarefa(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TELAS/IMAGENS/medical-11_icon-icons.com_73929.png"))); // NOI18N
        jMenuItem4.setText("Registro Clinico");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4abrirregistro(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TELAS/IMAGENS/vaccine_2_icon-icons.com_54420.png"))); // NOI18N
        jMenuItem1.setText("Vacina");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1abrirtelavacina(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TELAS/IMAGENS/medical-42_icon-icons.com_73897.png"))); // NOI18N
        jMenuItem2.setText("Receita");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2abrirtelareceita(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TELAS/IMAGENS/calendar_clock_schedule_icon-icons.com_51085.png"))); // NOI18N
        jMenuItem6.setText("Rotina de Tratamento");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6abrirtelarotina(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TELAS/IMAGENS/1-90_icon-icons.com_65672.png"))); // NOI18N
        jMenuItem8.setText("Tratador");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8abrirtelatratador(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TELAS/IMAGENS/business_application_addmale_useradd_insert_add_user_client_2312.png"))); // NOI18N
        jMenuItem11.setText("Usuario");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11aoabrirusuario(evt);
            }
        });
        jMenu3.add(jMenuItem11);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TELAS/IMAGENS/Doctor_Male_icon-icons.com_75051.png"))); // NOI18N
        jMenuItem7.setText("Veterinário");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7abrirtelavet(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TELAS/IMAGENS/info_1337.png"))); // NOI18N
        jMenu4.setText("Informacoes");

        jMenuItem14.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TELAS/IMAGENS/processinformation_proceso_2341.png"))); // NOI18N
        jMenuItem14.setText("Sobre");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aoclicaremsobre(evt);
            }
        });
        jMenu4.add(jMenuItem14);

        jMenuBar1.add(jMenu4);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TELAS/IMAGENS/SignOut_icon-icons.com_74704 (2).png"))); // NOI18N
        jMenu2.setText("Sair");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2parasairdosistema(evt);
            }
        });

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TELAS/IMAGENS/logout256_24927.png"))); // NOI18N
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5parasair(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem9telatarefa(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9telatarefa
        Tela_Inserir_Tarefa telinha = new Tela_Inserir_Tarefa(null, true);

        telinha.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9telatarefa

    private void jMenuItem10telaboletimdiario(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10telaboletimdiario

        Tela_Boletim_Diario telinha = new Tela_Boletim_Diario(null, true);

        telinha.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10telaboletimdiario

    private void jMenuItem4abrirregistro(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4abrirregistro
        Tela_Inserir_Registro_Clinico telinha = new Tela_Inserir_Registro_Clinico(null, true);

        telinha.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4abrirregistro

    private void jMenuItem1abrirtelavacina(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1abrirtelavacina
        Tela_Inserir_Vacina telinha = new Tela_Inserir_Vacina(null, true);

        telinha.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1abrirtelavacina

    private void jMenuItem2abrirtelareceita(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2abrirtelareceita
        Tela_Inserir_Receita telinha = new Tela_Inserir_Receita(null, true);

        telinha.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2abrirtelareceita

    private void jMenuItem6abrirtelarotina(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6abrirtelarotina

        Tela_Inserir_Rotina_Tratamento telinha = new Tela_Inserir_Rotina_Tratamento(null, true);

        telinha.setVisible(true);

    }//GEN-LAST:event_jMenuItem6abrirtelarotina

    private void jMenuItem7abrirtelavet(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7abrirtelavet
        Tela_Inserir_Veterinario telinha = new Tela_Inserir_Veterinario(null, true);

        telinha.setVisible(true);
    }//GEN-LAST:event_jMenuItem7abrirtelavet

    private void jMenuItem8abrirtelatratador(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8abrirtelatratador
        Tela_Inserir_Tratador telinha = new Tela_Inserir_Tratador(null, true);

        telinha.setVisible(true);
    }//GEN-LAST:event_jMenuItem8abrirtelatratador

    private void jMenuItem11aoabrirusuario(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11aoabrirusuario

        Tela_Inserir_Usuario telinha = new Tela_Inserir_Usuario(null, true);

        telinha.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem11aoabrirusuario

    private void jMenuItem5parasair(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5parasair
        System.exit(0);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5parasair

    private void jMenu2parasairdosistema(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2parasairdosistema
    System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2parasairdosistema

    private void abrirtelaanimal(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirtelaanimal
        
        Tela_Inserir_Animal telinha = new Tela_Inserir_Animal(null, true);

        telinha.setVisible(true);
        
// TODO add your handling code here:
    }//GEN-LAST:event_abrirtelaanimal

    private void aoabrirtela(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_aoabrirtela

        Date dataSistema = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        jLabel3.setText("DATA: "+formato.format(dataSistema));

        Timer timer = new Timer(1000,new hora());
        timer.start();
        
       

        // TODO add your handling code here:
    }//GEN-LAST:event_aoabrirtela

    private void aoclicaremsobre(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aoclicaremsobre

        JOptionPane.showMessageDialog(this,"Software construido por Victor Almeida e Adilson Souza para o trabalho do professor Daves.");
        // TODO add your handling code here:
    }//GEN-LAST:event_aoclicaremsobre

    private void jMenuItem15ttelaequipe(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ttelaequipe
        Tela_Exibir_Equipe telinha = new Tela_Exibir_Equipe(null, true);

        telinha.setVisible(true);
    }//GEN-LAST:event_jMenuItem15ttelaequipe

    private void jMenuItem16aobrircheck(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16aobrircheck

        Tela_Exibir_CheckList telinha = new Tela_Exibir_CheckList(null, true);

        telinha.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem16aobrircheck

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Tela_Principal_Administrador dialog = new Tela_Principal_Administrador(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jldata;
    private javax.swing.JLabel jlhora;
    // End of variables declaration//GEN-END:variables

class hora implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {

            Calendar now = Calendar.getInstance();
            jLabel2.setText("HORA: "+String.format("%1$tH:%1$tM:%1$tS", now));
        }
    }



}
